name: tf-checks

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  basic:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/basic/'
      provider: none

  complete:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/complete/'
      provider: none

  bindings:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/bindings/'
      provider: none

  pages:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './examples/pages/'
      provider: none
